name: Build
run-name: ${{ github.event_name == 'workflow_dispatch' && format('Build and Release v{0}', github.event.inputs.version) || github.event.commits[0].message }}

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (without "v" prefix)'
        required: true
        type: string
      beta:
        description: 'Beta release'
        default: false
        required: false
        type: boolean
      message:
        description: 'Message for releases (the text at the top of changelog)'
        default: ''
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test App
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Dependency Review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0

      - name: Set up JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          java-version-file: .github/.java-version
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Run unit tests
        id: unit_tests
        run: ./gradlew testDebugUnitTest

      - name: Verify SQLDelight migrations
        run: ./gradlew verifySqlDelightMigration

      - name: Upload test report
        if: steps.unit_tests.outcome == 'failure'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: test-report-${{ github.sha }}
          path: app/build/reports/tests/testDebugUnitTest

      - name: Build app
        run: ./gradlew assembleRelease -Pinclude-telemetry -Penable-updater

      - name: Upload APK
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: arm64-v8a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-arm64-v8a-release.apk

      - name: Upload mapping
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: mapping-${{ github.sha }}
          path: app/build/outputs/mapping/release

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Clouddark75/mihon'
        run: |
          echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Clouddark75/mihon'
        uses: r0adkll/sign-android-release@f30bdd30588842ac76044ecdbd4b6d0e3e813478
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Clean up build artifacts
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Clouddark75/mihon'
        shell: bash
        run: |
          set -euxo pipefail

          cd app/build/outputs/apk/release

          find . -name "*.apk" | sort

          UNIVERSAL=$(find . -name "*universal*signed*.apk" | head -n1 || true)
          ARM64=$(find . -name "*arm64-v8a*signed*.apk" | head -n1 || true)
          ARMV7=$(find . -name "*armeabi-v7a*signed*.apk" | head -n1 || true)
          X86=$(find . -name "*x86-release*signed*.apk" | head -n1 || true)
          X8664=$(find . -name "*x86_64*signed*.apk" | head -n1 || true)

          cp "$UNIVERSAL" "$GITHUB_WORKSPACE/mihon-${{ env.VERSION_TAG }}.apk"
          cp "$ARM64" "$GITHUB_WORKSPACE/mihon-arm64-v8a-${{ env.VERSION_TAG }}.apk"
          cp "$ARMV7" "$GITHUB_WORKSPACE/mihon-armeabi-v7a-${{ env.VERSION_TAG }}.apk"
          cp "$X86" "$GITHUB_WORKSPACE/mihon-x86-${{ env.VERSION_TAG }}.apk"
          cp "$X8664" "$GITHUB_WORKSPACE/mihon-x86_64-${{ env.VERSION_TAG }}.apk"

          cd "$GITHUB_WORKSPACE"

          echo "APK_UNIVERSAL_SHA=$(sha256sum mihon-${{ env.VERSION_TAG }}.apk | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "APK_ARM64_V8A_SHA=$(sha256sum mihon-arm64-v8a-${{ env.VERSION_TAG }}.apk | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "APK_ARMEABI_V7A_SHA=$(sha256sum mihon-armeabi-v7a-${{ env.VERSION_TAG }}.apk | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "APK_X86_SHA=$(sha256sum mihon-x86-${{ env.VERSION_TAG }}.apk | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "APK_X86_64_SHA=$(sha256sum mihon-x86_64-${{ env.VERSION_TAG }}.apk | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Clouddark75/mihon'
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Mihon ${{ env.VERSION_TAG }}
          body: |
            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.APK_UNIVERSAL_SHA }} |
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }} |
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }} |
            | x86 | ${{ env.APK_X86_SHA }} |
            | x86_64 | ${{ env.APK_X86_64_SHA }} |

            ## If you are unsure which version to choose then go with mihon-${{ env.VERSION_TAG }}.apk
          files: |
            mihon-${{ env.VERSION_TAG }}.apk
            mihon-arm64-v8a-${{ env.VERSION_TAG }}.apk
            mihon-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            mihon-x86-${{ env.VERSION_TAG }}.apk
            mihon-x86_64-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
